### ISSUE TITLE
HttpKernelInterface not found

### ISSUE THREAD

**Issue by jhoff** [intonate/tinker-zero#3]
Just created a new instance of Laravel Zero and installed tinker following the instructions.

Immediately, I get the following error message:

PHP Fatal error:  Interface 'Symfony\Component\HttpKernel\HttpKernelInterface' not found in /Users/jhoff/projects/uniform/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php on line 25

Fatal error: Interface 'Symfony\Component\HttpKernel\HttpKernelInterface' not found in /Users/jhoff/projects/uniform/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php on line 25

   Whoops\Exception\ErrorException  : Interface 'Symfony\Component\HttpKernel\HttpKernelInterface' not found

  at /Users/jhoff/projects/uniform/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php: 25
  21: use Symfony\Component\HttpFoundation\Request as SymfonyRequest;
  22: use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
  23: use Illuminate\Contracts\Foundation\Application as ApplicationContract;
  24:
  25: class Application extends Container implements ApplicationContract, HttpKernelInterface
  26: {
  27:     /**
  28:      * The Laravel framework version.
  29:      *
  30:      * @var string

**Comment by jhoff** [comment]
Looks like doing `composer require symfony/http-kernel` fixes the issue, but it seems like either this package or laravel-zero should provide it instead.

**Comment by nunomaduro** [comment]
@jhoff On the Laravel Zero 5.6 you will no longer have that issue. Please wait a few weeks. Meanwhile just install that symfony/http-kernel.
