### ISSUE TITLE
Bump laravel/tinker dependency

### ISSUE THREAD

**Issue by sergejostir** [intonate/tinker-zero#6]
Tinker 2.x is required for Laravel 7, so we cannot use tinker-zero with the latest laravel-zero package.

**Comment by nunomaduro** [comment]
@scrubmx Do you still have time to maintain this package? Otherwise we can transfer it to Laravel Zero org.

**Comment by scrubmx** [comment]
@nunomaduro Thanks for the heads up. Just [released a new version](https://github.com/intonate/tinker-zero/releases/tag/v1.1.0) to close this issue.
